import { createContext, useContext, useState, useEffect, useMemo, useCallback, ReactNode } from "react";

export type Lang = "az" | "ru" | "en";

const translations = {
  az: {
    // Nav
    home: "Ana Səhifə",
    categories: "Kateqoriyalar",
    about: "Haqqımızda",
    blog: "Blog",
    contact: "Əlaqə",
    login: "Daxil ol",
    register: "Qeydiyyat",
    logout: "Çıxış",
    dashboard: "İdarə Paneli",
    adminPanel: "Admin Panel",
    favorites: "Sevimlilər",
    profile: "Profil",
    support: "Dəstək",
    // Hero
    heroTitle: "Toyunuz üçün ən yaxşı xidmətlər",
    heroSub: "Azərbaycanın ən böyük toy xidmətləri platforması",
    heroBtn: "Xidmətlərə Bax",
    search: "Axtar...",
    // Categories
    allCategories: "Bütün Kateqoriyalar",
    services: "xidmət",
    // Listing
    price: "Qiymət aralığı",
    venuePrice: "Stul qiyməti",
    askPrice: "Qiymət soruşun",
    contactBtn: "WhatsApp ilə Əlaqə",
    back: "Geri",
    about_vendor: "Haqqında",
    store: "Mağazaya Bax",
    similarProducts: "Oxşar xidmətlər",
    otherProducts: "Digər kateqoriyalar",
    views: "baxış",
    noReviews: "",
    postedAt: "Yerləşdirildi",
    approvedAt: "Təsdiqləndi",
    mapTitle: "Xəritədə Yeri",
    mapBtn: "Google Maps-da Bax",
    venueInfo: "Məkan Məlumatları",
    district: "Rayon",
    capacity: "Tutum",
    amenities: "Mövcud xidmətlər",
    cuisine: "Mətbəx",
    share: "Paylaş",
    copy: "Kopyala",
    copied: "Link kopyalandı!",
    igCopy: "Link kopyalandı! İnstagram-da yapışdırın.",
    // Auth
    email: "E-poçt",
    password: "Şifrə",
    fullName: "Ad Soyad",
    asVendor: "Xidmət sahibi kimi qeydiyyatdan keç",
    forgotPass: "Şifrənizi unutdunuz?",
    resetPass: "Şifrəni Yenilə",
    sendReset: "Yeniləmə linki göndər",
    noAccount: "Hesabınız yoxdur?",
    hasAccount: "Hesabınız var?",
    // Password rules
    passMin: "Minimum 8 simvol",
    passUpper: "Böyük hərf (A-Z)",
    passLower: "Kiçik hərf (a-z)",
    passNumber: "Rəqəm (0-9)",
    passSpecial: "Xüsusi simvol (!@#$...)",
    passStrength: "Şifrə gücü",
    passWeak: "Zəif",
    passMedium: "Orta",
    passStrong: "Güclü",
    passVeryStrong: "Çox güclü",
    // Profile
    profileTitle: "Profil Məlumatları",
    phone: "Telefon",
    saveProfile: "Yadda Saxla",
    changePass: "Şifrəni Dəyiş",
    currentPass: "Cari şifrə",
    newPass: "Yeni şifrə",
    confirmPass: "Şifrəni təsdiqləyin",
    profileRequired: "Profilinizi tamamlayın",
    profileRequiredSub: "Davam etmək üçün ad, soyad və telefon nömrənizi daxil edin",
    // Vendor
    myServices: "Xidmətlərim",
    store_settings: "Mağaza",
    newService: "Yeni Xidmət",
    edit: "Redaktə",
    delete: "Sil",
    approved: "Təsdiqlənib",
    pending: "Gözləyir",
    // Capacity options
    cap50: "50-ə qədər",
    cap100: "50–100 nəfər",
    cap200: "100–200 nəfər",
    cap300: "200–300 nəfər",
    cap500: "300–500 nəfər",
    cap1000: "500+ nəfər",
    // Support steps
    step1Title: "Bizimlə Əlaqə Saxlayın",
    step1Desc: "WhatsApp, telefon və ya e-poçt vasitəsilə müraciət edin.",
    step2Title: "Problemizi İzah Edin",
    step2Desc: "Mütəxəssisimiz sizin ehtiyaclarınızı dinləyib anlayacaq.",
    step3Title: "Həll Alın",
    step3Desc: "Ən qısa zamanda sizə uyğun həll təklif ediləcək.",
    // Auth subtitles
    noServicesYet: "Hələ heç bir xidmət əlavə etməmisiniz",
    addFirstService: "İlk Xidmətinizi Əlavə Edin",
    newService: "Yeni Xidmət",
    logoSizeErr: "Logo 5MB-dan böyük ola bilməz",
    logoUploadErr: "Logo yüklənmədi",
    // Hero Slider
    slide1Title: "Xəyal Etdiyiniz Toyu",
    slide1High: "Birlikdə Quraq",
    slide1Sub: "Azərbaycanın ən böyük toy xidmətləri platforması",
    slide2Title: "Mükəmməl Məkanlar",
    slide2High: "Premium Xidmət",
    slide2Sub: "Bakının ən prestijli toy məkanları bir klikdə",
    slide3Title: "Peşəkar Fotoqraflar",
    slide3High: "Əbədi Anlar",
    slide3Sub: "Xüsusi anlarınızı professional şəkildə ölümsüzləşdirin",
    slide4Title: "Hər Detal",
    slide4High: "Sizin Üçün",
    slide4Sub: "Tort, dekorasiya, musiqi – hər şey bir platformada",
    // Index support block
    supportBlockTitle: "Professional Dəstək Xidməti",
    supportBlockDesc: "7/24 sizin üçün buradayıq. Toy planlaşdırma prosesində kömək alın.",
    learnMore: "Ətraflı",
    // Testimonials
    testimonialsTitle: "Müştəri Rəyləri",
    testimonialsSub: "Cütlüklərimizin ToyQur.az haqqında fikirləri",
    // Hero search
    searchPlaceholder: "Xidmət axtar... (məs. fotoqraf, məkan)",
    searchBtn: "Axtar",
    // Profile sub
    profileManage: "Şəxsi məlumatlarınızı idarə edin",
    // BlogPost
    blogBack: "Bloqa qayıt",
    articleNotFound: "Məqalə tapılmadı",
    // Blog post content keys
    bp1p1: "2026-cı il toy dünyasında yeni trendlər gətirdi. Bu il cütlüklər daha çox təbiətə yaxın, sadə lakin zərif üslubları seçirlər. Minimalist dekorasiyalar, torpaq tonlu rəng palitraları və yerli çiçəklərdən istifadə ön plana çıxır.",
    bp1p2: "Rəng palitrasında isə ağ, krem, şampan və yaşıl tonları dominantlıq edir. Gold aksessuarlar elegantlıq əlavə edir.",
    bp1p3: "Texnologiya da toylara daxil olmaqdadır. Canlı yayım, drone çəkilişləri və interaktiv qonaq kitabçaları bu ilin ən populyar yenilikləridir.",
    bp1p4: "Yemək trendinə gəldikdə, yerli məhsullardan hazırlanan menülər üstünlük təşkil edir. Tort dizaynlarında geometrik formalar populyardır.",
    bp1p5: "Musiqi sahəsində canlı ifaçılar ən çox tələb olunan seçimdir. DJ xidmətləri ilə birləşdirilmiş hibrid formatlar da populyarlaşır.",
    bp2p1: "Toy fotoqrafı seçimi toyunuzun ən vacib qərarlarından biridir. O gün keçəcək, amma fotoşəkillər əbədi qalacaq.",
    bp2p2: "Birincisi, fotoqrafın üslubunu araşdırın. Hər fotoqrafın öz bədii yanaşması var.",
    bp2p3: "İkincisi, təcrübəni yoxlayın. Ən azı 2-3 il toy fotoqrafiyası təcrübəsi olan birini seçmək tövsiyə olunur.",
    bp2p4: "Üçüncüsü, müqavilə və paketlərə diqqət edin. Çatdırılma müddətini öncədən müəyyənləşdirin.",
    bp2p5: "Nəhayət, fotoqrafla şəxsən görüşün. Kimyəvi uyğunluq çox vacibdir.",
    bp3p1: "Toy dekorasiyası toyunuzun atmosferini müəyyən edir. Düzgün seçimlə sadə məkanı nağıl dünyasına çevirə bilərsiniz.",
    bp3p2: "1. Rəng harmoniyası: Bir ana rəng seçin və 2-3 tamamlayıcı rənglə birləşdirin. Krem, ağ və gold klassik seçimdir.",
    bp3p3: "2. İşıqlandırma: Düzgün işıqlandırma atmosferin 50%-ni yaradır. İsti LED, şamlar romantik ab-hava yaradır.",
    bp3p4: "3. Çiçək seçimi: Mövsümi çiçəkləri üstün tutun — həm təzə olur, həm büdcəyə uyğundur.",
    bp3p5: "4. Masa düzümü: Qonaqlara rahat hiss etdirəcək düzüm seçin. Detallar fərqi yaradır.",
    bp3p6: "5. Giriş və fotozona: İlk təəssürat vacibdir. Fotozona qonaqlara xatirə şəkilləri çəkmək imkanı verir.",
    bp4p1: "Toy büdcəsi planlaşdırması xəyal etdiyiniz toyu reallaşdırmağın ən vacib addımıdır.",
    bp4p2: "İlk addım: Ümumi büdcənizi müəyyənləşdirin. Gözlənilməz xərclər üçün 10-15% ehtiyat ayırın.",
    bp4p3: "İkinci addım: Kateqoriyalar: Məkan (40-50%), fotoqraf (10-12%), geyim (8-10%), dekorasiya (7-10%), musiqi (5-8%).",
    bp4p4: "Üçüncü addım: Prioritetləri müəyyənləşdirin. Sizin üçün ən vacib olan nədir?",
    bp4p5: "Dördüncü addım: Qiymətləri müqayisə edin. ToyQur.az müxtəlif xidmət təminatçılarını bir yerdə göstərir.",
    bp4p6: "Beşinci addım: Danışıqlar aparın. Paket endirimlər və qeyri-pik günlər üçün xüsusi qiymətlər ola bilər.",
    // Testimonials data
    test1text: "ToyQur.az sayəsində bütün toy xidmətlərini bir yerdən tapdıq. Hər şey mükəmməl keçdi!",
    test2text: "Fotoqrafı və dekoratoru buradan seçdik. Nəticə gözləntilərimizi aşdı. Təşəkkürlər!",
    test3text: "Çox rahat platforma. Qiymətləri müqayisə etmək və rəyləri oxumaq çox kömək etdi.",
    contactNow: "İndi Bizimlə Əlaqə Saxlayın",
    supportHelp: "Toy planlaşdırma prosesində sizə kömək etməkdən məmnunuq",
    googleLogin: "Google ilə Daxil Ol",
    googleRegister: "Google ilə Qeydiyyat",
    orEmail: "və ya e-poçt ilə",
    authLoginSub: "Hesabınıza daxil olun",
    authRegisterSub: "Yeni hesab yaradın",
    authForgotSub: "E-poçtunuza yeniləmə linki göndərəcəyik",
    // ServiceForm
    editService: "Xidməti Redaktə Et",
    addService: "Yeni Xidmət Əlavə Et",
    saveService: "Yadda Saxla",
    addServiceBtn: "Əlavə Et",
    submitting: "Gözləyin...",
    minSeatPrice: "Min stul qiyməti (₼)",
    maxSeatPrice: "Maks stul qiyməti (₼)",
    minPrice: "Min qiymət (₼)",
    maxPrice: "Maks qiymət (₼)",
    // Sort / filter
    sortNewest: "Ən yeni",
    sortRating: "Ən yüksək reytinq",
    sortPriceAsc: "Qiymət: aşağıdan yuxarı",
    sortPriceDesc: "Qiymət: yuxarıdan aşağı",
    sortOldest: "Ən köhnə",
    allCities: "Bütün şəhərlər",
    allDistricts: "Bütün rayonlar",
    select: "Seçin",
    noResults: "Nəticə tapılmadı",
    noServices: "Xidmət yoxdur",
    noResultsMsg: "Seçdiyiniz filtrlərə uyğun xidmət tapılmadı. Filtrləri dəyişib yenidən cəhd edin.",
    noCatServices: "Bu kateqoriyada hələ heç bir xidmət yerləşdirilməyib.",
    resetFilters: "Filtrləri Sıfırla",
    goHome: "Ana səhifəyə qayıt",
    priceFilterLabel: "Qiymət aralığı (₼)",
    venuePriceLabel: "Stul qiyməti (₼)",
    // Hero
    heroLine1: "Xəyal Etdiyiniz Toyu",
    heroLine2: "Birlikdə Quraq",
    // CTA section
    ctaTitle: "Xidmət Sahibisiniz?",
    ctaDesc: "Platformamıza qoşulun, minlərlə cütlüyə çatın və biznesinizi böyüdün.",
    ctaBtn: "Xidmət Sahibi Olaraq Qeydiyyat",
    // Featured listings
    featuredOn: "Platformamızda",
    featuredTitle: "Bütün Xidmətlər",
    seeAll: "Hamısını gör",
    featuredSub: "Populyar toy xidmətlərini kəşf edin",
    sliderVenues: "Toy Məkanları",
    sliderOutfits: "Bəy & Gəlin Geyimləri",
    sliderOther: "Digər Xidmətlər",
    // Contact page
    contactTitle: "Əlaqə",
    contactSub: "Bizimlə əlaqə saxlayın — sizə kömək etməkdən məmnun olarıq!",
    contactEmail: "E-poçt",
    contactAddress: "Ünvan",
    contactCity: "Bakı, Azərbaycan",
    vendorCtaTitle: "Xidmət sahibisiniz?",
    vendorCtaDesc: "Platformamıza qoşulun, minlərlə cütlüyə çatın və biznesinizi böyüdün.",
    vendorCtaBtn: "Qeydiyyatdan Keçin",
    // Support page
    sup1Title: "7/24 Dəstək",
    sup1Desc: "Həftənin 7 günü, günün 24 saatı sizin üçün buradayıq.",
    sup2Title: "Peşəkar Komanda",
    sup2Desc: "Təcrübəli toy planlaşdırma mütəxəssislərimiz sizə ən uyğun xidmətləri tapır.",
    sup3Title: "Etibarlı Xidmət",
    sup3Desc: "Bütün xidmət sahibləri yoxlanılır.",
    sup4Title: "Sürətli Cavab",
    sup4Desc: "Müraciətlərinizə ən qısa zamanda cavab verilir.",
    supportTitle: "Professional Dəstək Xidməti",
    supportDesc: "ToyQur.az olaraq sizə toy planlaşdırma prosesinin hər mərhələsində professional dəstək göstəririk.",
    faqTitle: "Daha çox sualınız var?",
    // Vendor panel
    storeName: "Mağaza Tənzimləmələri",
    storeDesc: "Müştərilər məhsullarınıza baş vuranda sizin bütün məhsullarınızı bir yerdə görəcək",
    storeLogo: "Mağaza Logosu",
    storeLogoUpload: "Logo yüklə",
    storeBrandName: "Mağaza / Brend adı",
    storeAbout: "Mağaza haqqında",
    storeWA: "WhatsApp nömrəsi",
    // ServiceForm WA + edit limit
    whatsappField: "WhatsApp nömrəsi",
    whatsappRequired: "WhatsApp nömrəsi mütləqdir",
    whatsappPlaceholder: "+994 XX XXX XX XX",
    editLimitReached: "Bu xidməti artıq 2 dəfə redaktə etmisiniz. Daha çox redaktə mümkün deyil.",
    editCountLeft: "Qalan redaktə hüququ",
    editCountOf: "2-dən",
    svcUpdated: "Xidmət yeniləndi. Yenidən təsdiq gözlənilir.",
    svcAdded: "Xidmət əlavə edildi. Təsdiq gözlənilir.",
    fieldRequired: "Ad və kateqoriya daxil edin",
    priceRequired: "Minimum qiymət daxil edin",
    phoneRequired2: "Əlaqə nömrəsi mütləqdir",
    logoRequired2: "Logo şəkli mütləqdir",
    baRequired: "Bride Assistant üçün ad, soyad və yaş mütləqdir",
    baSkillRequired: "Ən azı bir bacarıq seçilməlidir",
    storeAddress: "Ünvan",
    completeProfile: "Mağazanızı tamamlayın",
    completeProfileMsg: "Logo, Mağaza adı və Telefon 1 doldurulduqdan sonra məhsul əlavə edə bilərsiniz.",
    completeProfileBtn: "Profili Tamamla",
    setupStore: "Əvvəlcə Mağazanızı Yaradın",
    setupStoreMsg: "Məhsul əlavə etmədən əvvəl mağazanızı qurun.",
    setupStoreBtn: "Mağazamı Qur",
    myStore: "Mağazama Bax",
    manageServices: "Xidmətlərinizi idarə edin",
    svcCount: "Xidmətlərim",
    deleteConfirm: "Bu xidməti silmək istədiyinizdən əminsiniz?",
    svcDeleted: "Xidmət silindi",
    svcLoadErr: "Xidmətlər yüklənmədi",
    profileFillRequired: "Əvvəlcə profil məlumatlarınızı tamamlayın",
    profileWarningTitle: "Profil məlumatlarınızı tamamlayın",
    profileWarningMsg: "Ad, soyad və telefon nömrəsi doldurulmalıdır.",
    // Booking statuses
    statusPending: "Gözləyir",
    statusConfirmed: "Təsdiqlənib",
    statusRejected: "Rədd edilib",
    statusCancelled: "Ləğv edilib",
    confirmBooking: "Təsdiqlə",
    rejectBooking: "Rədd et",
    noBookings: "Hələ heç bir rezervasiya yoxdur",
    bookingLoadErr: "Rezervasiyalar yüklənmədi",
    // Misc vendor form
    addMedia: "Əlavə et",
    mapHint: "Google Maps-da yeri tapıb Paylaş → Link kopyala edin və bura yapışdırın",
    formWarning: "Xidmət redaktə edildikdə yenidən təsdiq gözləniləcəkdir.",
    formPhoneNote: "Əlaqə nömrələri yalnız admin tərəfindən görüləcək.",
    // Footer
    copyright: "© 2026 ToyQur.az — Bütün hüquqlar qorunur.",
    // Profile page extra
    profileUpdated: "Profil yeniləndi!",
    passwordChanged: "Şifrə uğurla dəyişdirildi!",
    passwordChangeErr: "Şifrə dəyişdirilmədi",
    passwordMinErr: "Şifrə ən azı 6 simvol olmalıdır",
    defaultUser: "İstifadəçi",
    // VendorStore
    vendorStoreSuffix: "Mağaza",
    defaultStoreName: "Satıcı Mağazası",
    productsCount: "məhsul",
    catCount: "kateqoriya",
    // About page
    aboutTitle: "Haqqımızda",
    aboutSub: "ToyQur.az Azərbaycanın ilk və ən böyük toy xidmətləri platformasıdır. Məqsədimiz cütlüklərə xəyal etdikləri toyu asanlıqla planlaşdırmağa kömək etməkdir.",
    missionTitle: "Missiyamız",
    missionText: "Toy planlaşdırma prosesini sadələşdirmək, xidmət sahibləri ilə müştəriləri bir araya gətirmək və hər kəsin xəyal etdiyi toyu reallaşdırmasına kömək etmək.",
    feat1Title: "Ehtiras",
    feat1Desc: "Hər toyun unikal və xüsusi olduğuna inanırıq. Biz sevgi ilə işləyirik.",
    feat2Title: "Geniş Şəbəkə",
    feat2Desc: "Azərbaycanın hər bölgəsindən yüzlərlə peşəkar xidmət sahibi ilə əməkdaşlıq edirik.",
    feat3Title: "Etibarlılıq",
    feat3Desc: "Bütün xidmət sahibləri yoxlanılır və müştəri rəyləri şəffaf şəkildə paylaşılır.",
    feat4Title: "Keyfiyyət",
    feat4Desc: "Yalnız ən yaxşı xidmət sahiblərini platformamızda təqdim edirik.",
    // Blog page
    blogSub: "Toy planlaşdırma haqqında faydalı məqalələr, peşəkar tövsiyələr və ilham verən ideyalar",
    readMore: "Daha çox oxu",
    // Profile page
    myProfile: "Profilim",
    profileSub: "Şəxsi məlumatlarınızı idarə edin",
    personalInfo: "Şəxsi Məlumatlar",
    fullNameLabel: "Ad və Soyad",
    phoneLabel: "Telefon nömrəsi",
    emailLabel: "E-poçt",
    emailNote: "E-poçt dəyişdirilə bilməz",
    emailVerified: "E-poçt təsdiqlənib",
    saveChanges: "Dəyişiklikləri Saxla",
    changePassTitle: "Şifrəni Dəyiş",
    newPassLabel: "Yeni Şifrə",
    confirmPassLabel: "Yeni Şifrəni Təsdiqlə",
    passNoMatch: "Şifrələr uyğun gəlmir",
    changing: "Dəyişdirilir...",
    // Favorites page
    favoritesTitle: "Sevimlilər",
    favoritesLoginMsg: "Sevimliləri görmək üçün hesabınıza daxil olun",
    favoritesEmpty: "Hələ heç bir sevimlilər yoxdur",
    favoritesEmptySub: "Xidmətlərə baxın və bəyəndiklərinizi saxlayın",
    removeFromFav: "Sevimlilərdən sil",
    browseSvcs: "Xidmətlərə Bax",
    // Blog posts
    blog1Title: "2026-cı il üçün Toy Trendləri",
    blog1Excerpt: "Bu il toylar üçün ən populyar rənglər, dekorasiya üslubları və məkan seçimləri haqqında ətraflı məlumat.",
    blog1Tag: "Trendlər",
    blog2Title: "Mükəmməl Toy Fotoqrafını Necə Seçmək Olar",
    blog2Excerpt: "Toy fotoqrafı seçərkən diqqət etməli olduğunuz 5 vacib məqam.",
    blog2Tag: "Məsləhət",
    blog3Title: "Toy Dekorasiyasında 5 Əsas Qayda",
    blog3Excerpt: "Toyunuzun dekorasiyasını planlaşdırarkən nəzərə almalı olduğunuz əsas qaydalar.",
    blog3Tag: "Dekorasiya",
    blog4Title: "Toy Büdcənizi Necə Planlaşdırmalı",
    blog4Excerpt: "Büdcənizi düzgün bölüşdürərək xəyal etdiyiniz toyu reallaşdırın.",
    blog4Tag: "Büdcə",
    // Categories page
    sortNewest: "Ən yeni",
    sortRating: "Ən yüksək reytinq",
    sortPriceAsc: "Qiymət: aşağıdan yuxarı",
    sortPriceDesc: "Qiymət: yuxarıdan aşağı",
    sortOldest: "Ən köhnə",
    noResults: "Nəticə tapılmadı",
    noServices: "Xidmət yoxdur",
    noResultsDesc: "Seçdiyiniz filtrlərə uyğun xidmət tapılmadı. Filtrləri dəyişib yenidən cəhd edin.",
    resetFilters: "Filtrləri Sıfırla",
    searchPlaceholder: "Xidmət axtar...",
    filters: "Filtrlər",
    priceVenue: "Stul qiyməti (₼)",
    priceRange: "Qiymət aralığı (₼)",
    cityLabel: "Şəhər",
    allCities: "Bütün şəhərlər",
    districtLabel: "Rayon",
    allDistricts: "Bütün rayonlar",
    guestLabel: "Qonaq sayı",
    selectOption: "Seçin",
    searchHero: "Xidmət axtar... (məs. fotoqraf, məkan)",
    // Contact page
    contactTitle: "Əlaqə",
    contactSub: "Bizimlə əlaqə saxlayın — sizə kömək etməkdən məmnun olarıq!",
    contactPhone: "Telefon",
    contactAddress: "Ünvan",
    contactCity: "Bakı, Azərbaycan",
    vendorCTA: "Xidmət sahibisiniz?",
    vendorCTADesc: "Platformamıza qoşulun, minlərlə cütlüyə çatın və biznesinizi böyüdün.",
    registerNow: "Qeydiyyatdan Keçin",
    // Support page
    sup1Title: "7/24 Dəstək",

    sup2Title: "Peşəkar Komanda",
    sup2Desc: "Təcrübəli toy planlaşdırma mütəxəssislərimiz sizə ən uyğun xidmətləri tapmaqda kömək edəcək.",
    sup3Title: "Etibarlı Xidmət",
    sup3Desc: "Bütün xidmət sahibləri yoxlanılır. Hər hansı problem yarandıqda biz vasitəçi olaraq müdaxilə edirik.",
    sup4Title: "Sürətli Cavab",
    sup4Desc: "Müraciətlərinizə ən qısa zamanda cavab verilir. Ortalama cavab müddəti 15 dəqiqədir.",
    supStep1Title: "Bizimlə Əlaqə Saxlayın",
    supStep1Desc: "WhatsApp, telefon və ya e-poçt vasitəsilə müraciət edin.",
    supStep2Title: "Probleminizi İzah Edin",
    supStep2Desc: "Mütəxəssisimiz sizin ehtiyaclarınızı dinləyib anlayacaq.",
    supStep3Title: "Həll Alın",
    supStep3Desc: "Ən qısa zamanda sizə uyğun həll təklif ediləcək.",
    // Vendor
    vendorStoreFallback: "Satıcı Mağazası",
    heroSearchPlaceholder: "Xidmət axtar... (məs. fotoqraf, məkan)",
    // Category names
    "cat.wedding-hall": "Toy zalları",
    "cat.banquet-hall": "Banket zalları",
    "cat.photographer": "Fotoqraf",
    "cat.videographer": "Videoqraf",
    "cat.cake": "Tort",
    "cat.xonca": "Xonça",
    "cat.invitation": "Dəvətnamə",
    "cat.mc": "Aparıcı",
    "cat.car": "Toy maşınları",
    "cat.decoration": "Dekor & Dizayn",
    "cat.music": "Canlı musiqi qrupu",
    "cat.dress": "Gəlinlik",
    "cat.groom-suit": "Bəy geyimləri",
    "cat.dj": "DJ",
    "cat.singer": "Müğənni",
    "cat.dance-group": "Rəqs qrupu",
    "cat.beauty-salon": "Gözəllik salonu",
    
    "cat.bride-assistant": "Gəlin köməkçisi",
    "cat.mobilograf": "Mobiloqraf",
    "cat.buket": "Buket",
    "cat.gelinlik-buketi": "Gəlinlik buketi",
    "cat.group.venues": "Məkanlar",
    "cat.group.other": "Digər Xidmətlər",
    // Toast messages
    favAdded: "Sevimlilərə əlavə edildi",
    favRemoved: "Sevimlilərdən silindi",
    favLogin: "Sevimlilərə əlavə etmək üçün daxil olun",
    saveSuccess: "Yadda saxlandı!",
    brandSaved: "Mağaza məlumatları yadda saxlandı!",
    logoRequired: "Mağaza logosu mütləqdir",
    phoneRequired: "Telefon 1 mütləqdir",
    brandRequired: "Mağaza adı mütləqdir",
    saving: "Saxlanır...",
    updating: "Yenilənir...",
    // General
    loading: "Yüklənir...",
    notFound: "Tapılmadı",
    error: "Xəta baş verdi",
  },
  ru: {
    home: "Главная",
    categories: "Категории",
    about: "О нас",
    blog: "Блог",
    contact: "Контакт",
    login: "Войти",
    register: "Регистрация",
    logout: "Выход",
    dashboard: "Панель управления",
    adminPanel: "Панель админа",
    favorites: "Избранное",
    profile: "Профиль",
    support: "Поддержка",
    heroTitle: "Лучшие услуги для вашей свадьбы",
    heroSub: "Крупнейшая платформа свадебных услуг Азербайджана",
    heroBtn: "Посмотреть услуги",
    search: "Поиск...",
    allCategories: "Все категории",
    services: "услуг",
    price: "Диапазон цен",
    venuePrice: "Цена на стул",
    askPrice: "Уточнить цену",
    contactBtn: "Связаться через WhatsApp",
    back: "Назад",
    about_vendor: "О нас",
    store: "Перейти в магазин",
    similarProducts: "Похожие услуги",
    otherProducts: "Другие категории",
    views: "просмотров",
    noReviews: "",
    postedAt: "Опубликовано",
    approvedAt: "Одобрено",
    mapTitle: "На карте",
    mapBtn: "Открыть в Google Maps",
    venueInfo: "Информация о месте",
    district: "Район",
    capacity: "Вместимость",
    amenities: "Доступные услуги",
    cuisine: "Кухня",
    share: "Поделиться",
    copy: "Копировать",
    copied: "Ссылка скопирована!",
    igCopy: "Ссылка скопирована! Вставьте в Instagram.",
    email: "E-mail",
    password: "Пароль",
    fullName: "Имя Фамилия",
    asVendor: "Зарегистрироваться как поставщик услуг",
    forgotPass: "Забыли пароль?",
    resetPass: "Сброс пароля",
    sendReset: "Отправить ссылку",
    noAccount: "Нет аккаунта?",
    hasAccount: "Уже есть аккаунт?",
    passMin: "Минимум 8 символов",
    passUpper: "Заглавная буква (A-Z)",
    passLower: "Строчная буква (a-z)",
    passNumber: "Цифра (0-9)",
    passSpecial: "Спецсимвол (!@#$...)",
    passStrength: "Надёжность пароля",
    passWeak: "Слабый",
    passMedium: "Средний",
    passStrong: "Сильный",
    passVeryStrong: "Очень сильный",
    profileTitle: "Данные профиля",
    phone: "Телефон",
    saveProfile: "Сохранить",
    changePass: "Изменить пароль",
    currentPass: "Текущий пароль",
    newPass: "Новый пароль",
    confirmPass: "Подтвердите пароль",
    profileRequired: "Заполните профиль",
    profileRequiredSub: "Введите имя, фамилию и номер телефона для продолжения",
    myServices: "Мои услуги",
    store_settings: "Магазин",
    newService: "Новая услуга",
    edit: "Редактировать",
    delete: "Удалить",
    approved: "Одобрено",
    pending: "Ожидает",
    cap50: "до 50",
    cap100: "50–100 гостей",
    cap200: "100–200 гостей",
    cap300: "200–300 гостей",
    cap500: "300–500 гостей",
    cap1000: "500+ гостей",
    step1Title: "Свяжитесь с нами",
    step1Desc: "Обратитесь через WhatsApp, телефон или e-mail.",
    step2Title: "Опишите проблему",
    step2Desc: "Наш специалист выслушает и поймёт ваши потребности.",
    step3Title: "Получите решение",
    step3Desc: "В кратчайшие сроки вам будет предложено подходящее решение.",
    noServicesYet: "Услуг ещё нет",
    addFirstService: "Добавьте первую услугу",
    newService: "Новая услуга",
    logoSizeErr: "Логотип не может быть больше 5МБ",
    logoUploadErr: "Не удалось загрузить логотип",
    slide1Title: "Свадьбу вашей мечты",
    slide1High: "Создадим вместе",
    slide1Sub: "Крупнейшая платформа свадебных услуг Азербайджана",
    slide2Title: "Идеальные площадки",
    slide2High: "Премиум сервис",
    slide2Sub: "Самые престижные свадебные залы Баку в один клик",
    slide3Title: "Профессиональные фотографы",
    slide3High: "Вечные моменты",
    slide3Sub: "Увековечьте особые моменты профессионально",
    slide4Title: "Каждая деталь",
    slide4High: "Для вас",
    slide4Sub: "Торт, декор, музыка — всё на одной платформе",
    supportBlockTitle: "Профессиональная служба поддержки",
    supportBlockDesc: "Мы здесь для вас 24/7. Получите помощь в планировании свадьбы.",
    learnMore: "Подробнее",
    testimonialsTitle: "Отзывы клиентов",
    testimonialsSub: "Что говорят пары о ToyQur.az",
    searchPlaceholder: "Поиск услуг... (напр. фотограф, зал)",
    searchBtn: "Найти",
    profileManage: "Управляйте личными данными",
    blogBack: "Вернуться в блог",
    articleNotFound: "Статья не найдена",
    bp1p1: "2026 год принёс новые тренды в мире свадеб. Пары всё чаще выбирают стили, близкие к природе.",
    bp1p2: "В палитре доминируют белый, кремовый, шампанский и зелёный тона. Золотые детали добавляют элегантность.",
    bp1p3: "Технологии продолжают входить на свадьбы: прямые трансляции, съёмка дронами.",
    bp1p4: "В меню преобладают блюда из местных продуктов. Геометрические торты в моде.",
    bp1p5: "Живые исполнители — самый популярный выбор. Гибридные форматы с DJ набирают популярность.",
    bp2p1: "Выбор свадебного фотографа — одно из важнейших решений. Фотографии останутся навсегда.",
    bp2p2: "Во-первых, изучите стиль фотографа. У каждого свой художественный подход.",
    bp2p3: "Во-вторых, проверьте опыт. Рекомендуется выбирать с опытом от 2-3 лет.",
    bp2p4: "В-третьих, изучите договор и пакеты. Уточните количество фото и сроки.",
    bp2p5: "Наконец, встретьтесь лично. Химия очень важна.",
    bp3p1: "Свадебный декор определяет атмосферу. Правильный выбор превратит простое место в сказку.",
    bp3p2: "1. Цветовая гармония: выберите один основной цвет и 2-3 дополнительных.",
    bp3p3: "2. Освещение: правильный свет создаёт 50% атмосферы. Тёплые LED и свечи.",
    bp3p4: "3. Цветы: отдавайте предпочтение сезонным — свежие и доступные.",
    bp3p5: "4. Сервировка: комфортная расстановка столов. Детали важны.",
    bp3p6: "5. Вход и фотозона: первое впечатление важно. Фотозона для гостей.",
    bp4p1: "Планирование бюджета — важнейший шаг к свадьбе вашей мечты.",
    bp4p2: "Шаг 1: Определите общий бюджет. Оставьте 10-15% резерв.",
    bp4p3: "Шаг 2: Зал (40-50%), фото (10-12%), наряды (8-10%), декор (7-10%), музыка (5-8%).",
    bp4p4: "Шаг 3: Определите приоритеты. Что для вас важнее всего?",
    bp4p5: "Шаг 4: Сравнивайте цены. ToyQur.az собирает всех поставщиков в одном месте.",
    bp4p6: "Шаг 5: Торгуйтесь. Пакетные скидки и специальные цены в непиковые дни.",
    test1text: "Благодаря ToyQur.az нашли все услуги в одном месте. Всё прошло идеально!",
    test2text: "Нашли фотографа и декоратора здесь. Результат превзошёл ожидания. Спасибо!",
    test3text: "Очень удобная платформа. Сравнение цен и чтение отзывов очень помогло.",
    contactNow: "Свяжитесь с нами сейчас",
    supportHelp: "Мы рады помочь вам в процессе планирования свадьбы",
    googleLogin: "Войти через Google",
    googleRegister: "Регистрация через Google",
    orEmail: "или с помощью e-mail",
    authLoginSub: "Войдите в свой аккаунт",
    authRegisterSub: "Создайте новый аккаунт",
    authForgotSub: "Мы отправим ссылку для сброса пароля на ваш e-mail",
    editService: "Редактировать услугу",
    addService: "Добавить новую услугу",
    saveService: "Сохранить",
    addServiceBtn: "Добавить",
    submitting: "Подождите...",
    minSeatPrice: "Мин. цена на стул (₼)",
    maxSeatPrice: "Макс. цена на стул (₼)",
    minPrice: "Мин. цена (₼)",
    maxPrice: "Макс. цена (₼)",
    sortNewest: "Новейшие",
    sortRating: "Высокий рейтинг",
    sortPriceAsc: "Цена: по возрастанию",
    sortPriceDesc: "Цена: по убыванию",
    sortOldest: "Старейшие",
    allCities: "Все города",
    allDistricts: "Все районы",
    select: "Выбрать",
    noResults: "Результатов нет",
    noServices: "Услуг нет",
    noResultsMsg: "По вашим фильтрам услуги не найдены. Измените фильтры и попробуйте снова.",
    noCatServices: "В этой категории ещё нет услуг.",
    resetFilters: "Сбросить фильтры",
    goHome: "На главную",
    priceFilterLabel: "Диапазон цен (₼)",
    venuePriceLabel: "Цена на стул (₼)",
    heroLine1: "Свадьбу вашей мечты",
    heroLine2: "Создадим вместе",
    ctaTitle: "Вы поставщик услуг?",
    ctaDesc: "Присоединяйтесь к платформе, охватите тысячи пар и развивайте бизнес.",
    ctaBtn: "Зарегистрироваться как поставщик",
    featuredOn: "На платформе",
    featuredTitle: "Все услуги",
    seeAll: "Смотреть все",
    featuredSub: "Откройте для себя популярные свадебные услуги",
    sliderVenues: "Свадебные залы",
    sliderOutfits: "Наряды жениха и невесты",
    sliderOther: "Другие услуги",
    contactTitle: "Контакт",
    contactSub: "Свяжитесь с нами — мы рады помочь!",
    contactEmail: "E-mail",
    contactAddress: "Адрес",
    contactCity: "Баку, Азербайджан",
    vendorCtaTitle: "Вы поставщик услуг?",
    vendorCtaDesc: "Присоединяйтесь к платформе, охватите тысячи пар и развивайте бизнес.",
    vendorCtaBtn: "Зарегистрироваться",
    sup1Title: "Поддержка 24/7",
    sup1Desc: "Мы здесь для вас 7 дней в неделю, 24 часа в сутки.",
    sup2Title: "Профессиональная команда",
    sup2Desc: "Наши опытные специалисты помогут найти лучшие услуги.",
    sup3Title: "Надёжный сервис",
    sup3Desc: "Все поставщики услуг проверены.",
    sup4Title: "Быстрый ответ",
    sup4Desc: "Ответ на ваши запросы в кратчайшие сроки.",
    supportTitle: "Профессиональная служба поддержки",
    supportDesc: "ToyQur.az обеспечивает профессиональную поддержку на каждом этапе планирования свадьбы.",
    faqTitle: "Остались вопросы?",
    storeName: "Настройки магазина",
    storeDesc: "Покупатели увидят все ваши товары в одном месте",
    storeLogo: "Логотип магазина",
    storeLogoUpload: "Загрузить логотип",
    storeBrandName: "Название / бренд магазина",
    storeAbout: "О магазине",
    storeWA: "Номер WhatsApp",
    whatsappField: "Номер WhatsApp",
    whatsappRequired: "Номер WhatsApp обязателен",
    whatsappPlaceholder: "+994 XX XXX XX XX",
    editLimitReached: "Вы уже редактировали эту услугу 2 раза. Дальнейшее редактирование невозможно.",
    editCountLeft: "Осталось правок",
    editCountOf: "из 2",
    svcUpdated: "Услуга обновлена. Ожидает повторного подтверждения.",
    svcAdded: "Услуга добавлена. Ожидает подтверждения.",
    fieldRequired: "Введите название и категорию",
    priceRequired: "Введите минимальную цену",
    phoneRequired2: "Номер телефона обязателен",
    logoRequired2: "Логотип обязателен",
    baRequired: "Для Bride Assistant необходимо указать имя, фамилию и возраст",
    baSkillRequired: "Необходимо выбрать хотя бы один навык",
    storeAddress: "Адрес",
    completeProfile: "Заполните ваш магазин",
    completeProfileMsg: "После заполнения логотипа, названия и телефона вы сможете добавлять товары.",
    completeProfileBtn: "Заполнить профиль",
    setupStore: "Сначала создайте магазин",
    setupStoreMsg: "Перед добавлением товара создайте магазин.",
    setupStoreBtn: "Создать магазин",
    myStore: "Мой магазин",
    manageServices: "Управляйте своими услугами",
    svcCount: "Мои услуги",
    deleteConfirm: "Вы уверены, что хотите удалить эту услугу?",
    svcDeleted: "Услуга удалена",
    svcLoadErr: "Не удалось загрузить услуги",
    profileFillRequired: "Сначала заполните данные профиля",
    profileWarningTitle: "Заполните данные профиля",
    profileWarningMsg: "Необходимо заполнить имя, фамилию и номер телефона.",
    statusPending: "Ожидает",
    statusConfirmed: "Подтверждено",
    statusRejected: "Отклонено",
    statusCancelled: "Отменено",
    confirmBooking: "Подтвердить",
    rejectBooking: "Отклонить",
    noBookings: "Бронирований ещё нет",
    bookingLoadErr: "Не удалось загрузить бронирования",
    addMedia: "Добавить",
    mapHint: "Найдите место на Google Maps, нажмите Поделиться → Копировать ссылку и вставьте сюда",
    formWarning: "После редактирования услуга будет снова ожидать подтверждения.",
    formPhoneNote: "Номера телефонов видны только администратору.",
    copyright: "© 2026 ToyQur.az — Все права защищены.",
    profileUpdated: "Профиль обновлён!",
    passwordChanged: "Пароль успешно изменён!",
    passwordChangeErr: "Не удалось изменить пароль",
    passwordMinErr: "Пароль должен содержать не менее 6 символов",
    defaultUser: "Пользователь",
    vendorStoreSuffix: "Магазин",
    defaultStoreName: "Магазин продавца",
    productsCount: "товаров",
    catCount: "категорий",
    aboutTitle: "О нас",
    aboutSub: "ToyQur.az — первая и крупнейшая платформа свадебных услуг Азербайджана. Наша цель — помочь парам легко спланировать свадьбу своей мечты.",
    missionTitle: "Наша миссия",
    missionText: "Упростить планирование свадьбы, объединить поставщиков услуг с клиентами и помочь каждому воплотить свадьбу мечты.",
    feat1Title: "Страсть",
    feat1Desc: "Мы верим, что каждая свадьба уникальна. Мы работаем с любовью.",
    feat2Title: "Широкая сеть",
    feat2Desc: "Сотрудничаем с сотнями профессионалов из каждого региона Азербайджана.",
    feat3Title: "Надёжность",
    feat3Desc: "Все поставщики услуг проверены, отзывы клиентов публикуются прозрачно.",
    feat4Title: "Качество",
    feat4Desc: "Представляем на платформе только лучших поставщиков услуг.",
    blogSub: "Полезные статьи, профессиональные советы и вдохновляющие идеи о планировании свадьбы",
    readMore: "Читать далее",
    myProfile: "Мой профиль",
    profileSub: "Управляйте личными данными",
    personalInfo: "Личные данные",
    fullNameLabel: "Имя и фамилия",
    phoneLabel: "Номер телефона",
    emailLabel: "E-mail",
    emailNote: "E-mail нельзя изменить",
    emailVerified: "E-mail подтверждён",
    saveChanges: "Сохранить изменения",
    changePassTitle: "Изменить пароль",
    newPassLabel: "Новый пароль",
    confirmPassLabel: "Подтвердите пароль",
    passNoMatch: "Пароли не совпадают",
    changing: "Изменение...",
    favoritesTitle: "Избранное",
    favoritesLoginMsg: "Войдите, чтобы увидеть избранное",
    favoritesEmpty: "Избранного ещё нет",
    favoritesEmptySub: "Просмотрите услуги и сохраните понравившееся",
    removeFromFav: "Удалить из избранного",
    browseSvcs: "Смотреть услуги",
    blog1Title: "Свадебные тренды 2026 года",
    blog1Excerpt: "Подробная информация о самых популярных цветах, стилях декора и выборе площадок для свадеб в этом году.",
    blog1Tag: "Тренды",
    blog2Title: "Как выбрать идеального свадебного фотографа",
    blog2Excerpt: "5 важных моментов, на которые следует обратить внимание при выборе свадебного фотографа.",
    blog2Tag: "Советы",
    blog3Title: "5 основных правил свадебного декора",
    blog3Excerpt: "Основные правила при планировании декора вашей свадьбы.",
    blog3Tag: "Декор",
    blog4Title: "Как планировать свадебный бюджет",
    blog4Excerpt: "Правильно распределите бюджет и воплотите свадьбу своей мечты.",
    blog4Tag: "Бюджет",
    sortNewest: "Сначала новые",
    sortRating: "По рейтингу",
    sortPriceAsc: "Цена: по возрастанию",
    sortPriceDesc: "Цена: по убыванию",
    sortOldest: "Сначала старые",
    noResults: "Результатов нет",
    noServices: "Услуг нет",
    noResultsDesc: "По выбранным фильтрам услуг не найдено. Измените фильтры и попробуйте снова.",
    resetFilters: "Сбросить фильтры",
    searchPlaceholder: "Поиск услуг...",
    filters: "Фильтры",
    priceVenue: "Цена на стул (₼)",
    priceRange: "Диапазон цен (₼)",
    cityLabel: "Город",
    allCities: "Все города",
    districtLabel: "Район",
    allDistricts: "Все районы",
    guestLabel: "Количество гостей",
    selectOption: "Выбрать",
    searchHero: "Поиск услуг... (напр. фотограф, зал)",
    contactTitle: "Контакт",
    contactSub: "Свяжитесь с нами — мы рады помочь вам!",
    contactPhone: "Телефон",
    contactAddress: "Адрес",
    contactCity: "Баку, Азербайджан",
    vendorCTA: "Вы поставщик услуг?",
    vendorCTADesc: "Присоединяйтесь к платформе, охватите тысячи пар и развивайте свой бизнес.",
    registerNow: "Зарегистрироваться",
    sup1Title: "Поддержка 7/24",
    sup1Desc: "Мы здесь для вас 7 дней в неделю, 24 часа в сутки. Получите помощь в планировании свадьбы в любой момент.",
    sup2Title: "Профессиональная команда",
    sup2Desc: "Наши опытные специалисты по планированию свадеб помогут найти вам самые подходящие услуги.",
    sup3Title: "Надёжный сервис",
    sup3Desc: "Все поставщики услуг проверены. При возникновении проблем мы выступаем посредником.",
    sup4Title: "Быстрый ответ",
    sup4Desc: "На ваши обращения отвечают в кратчайшие сроки. Среднее время ответа — 15 минут.",
    supStep1Title: "Свяжитесь с нами",
    supStep1Desc: "Обратитесь через WhatsApp, телефон или e-mail.",
    supStep2Title: "Опишите проблему",
    supStep2Desc: "Наш специалист выслушает и поймёт ваши потребности.",
    supStep3Title: "Получите решение",
    supStep3Desc: "В кратчайшие сроки вам предложат подходящее решение.",
    vendorStoreFallback: "Магазин продавца",
    heroSearchPlaceholder: "Поиск услуг... (напр. фотограф, зал)",
    "cat.wedding-hall": "Свадебные залы",
    "cat.banquet-hall": "Банкетные залы",
    "cat.photographer": "Фотограф",
    "cat.videographer": "Видеограф",
    "cat.cake": "Торт",
    "cat.xonca": "Хончa",
    "cat.invitation": "Приглашения",
    "cat.mc": "Ведущий",
    "cat.car": "Свадебные авто",
    "cat.decoration": "Декор & Дизайн",
    "cat.music": "Живая музыка",
    "cat.dress": "Свадебное платье",
    "cat.groom-suit": "Костюм жениха",
    "cat.dj": "DJ",
    "cat.singer": "Певец",
    "cat.dance-group": "Танцевальная группа",
    "cat.beauty-salon": "Салон красоты",
    
    "cat.bride-assistant": "Помощница невесты",
    "cat.mobilograf": "Мобилограф",
    "cat.buket": "Букет",
    "cat.gelinlik-buketi": "Свадебный букет",
    "cat.group.venues": "Залы",
    "cat.group.other": "Другие услуги",
    favAdded: "Добавлено в избранное",
    favRemoved: "Удалено из избранного",
    favLogin: "Войдите, чтобы добавить в избранное",
    saveSuccess: "Сохранено!",
    brandSaved: "Данные магазина сохранены!",
    logoRequired: "Логотип магазина обязателен",
    phoneRequired: "Телефон 1 обязателен",
    brandRequired: "Название магазина обязательно",
    saving: "Сохранение...",
    updating: "Обновление...",
    loading: "Загрузка...",
    notFound: "Не найдено",
    error: "Произошла ошибка",
  },
  en: {
    home: "Home",
    categories: "Categories",
    about: "About",
    blog: "Blog",
    contact: "Contact",
    login: "Sign In",
    register: "Sign Up",
    logout: "Sign Out",
    dashboard: "Dashboard",
    adminPanel: "Admin Panel",
    favorites: "Favorites",
    profile: "Profile",
    support: "Support",
    heroTitle: "The best services for your wedding",
    heroSub: "Azerbaijan's largest wedding services platform",
    heroBtn: "Browse Services",
    search: "Search...",
    allCategories: "All Categories",
    services: "services",
    price: "Price range",
    venuePrice: "Per seat price",
    askPrice: "Ask for price",
    contactBtn: "Contact via WhatsApp",
    back: "Back",
    about_vendor: "About",
    store: "Visit Store",
    similarProducts: "Similar services",
    otherProducts: "Other categories",
    views: "views",
    noReviews: "",
    postedAt: "Posted",
    approvedAt: "Approved",
    mapTitle: "Location on Map",
    mapBtn: "Open in Google Maps",
    venueInfo: "Venue Details",
    district: "District",
    capacity: "Capacity",
    amenities: "Available services",
    cuisine: "Cuisine",
    share: "Share",
    copy: "Copy link",
    copied: "Link copied!",
    igCopy: "Link copied! Paste it on Instagram.",
    email: "Email",
    password: "Password",
    fullName: "Full Name",
    asVendor: "Register as a service provider",
    forgotPass: "Forgot password?",
    resetPass: "Reset Password",
    sendReset: "Send reset link",
    noAccount: "Don't have an account?",
    hasAccount: "Already have an account?",
    passMin: "Minimum 8 characters",
    passUpper: "Uppercase letter (A-Z)",
    passLower: "Lowercase letter (a-z)",
    passNumber: "Number (0-9)",
    passSpecial: "Special character (!@#$...)",
    passStrength: "Password strength",
    passWeak: "Weak",
    passMedium: "Medium",
    passStrong: "Strong",
    passVeryStrong: "Very strong",
    profileTitle: "Profile Details",
    phone: "Phone",
    saveProfile: "Save",
    changePass: "Change Password",
    currentPass: "Current password",
    newPass: "New password",
    confirmPass: "Confirm password",
    profileRequired: "Complete your profile",
    profileRequiredSub: "Enter your name and phone number to continue",
    myServices: "My Services",
    store_settings: "Store",
    newService: "New Service",
    edit: "Edit",
    delete: "Delete",
    approved: "Approved",
    pending: "Pending",
    cap50: "Up to 50",
    cap100: "50–100 guests",
    cap200: "100–200 guests",
    cap300: "200–300 guests",
    cap500: "300–500 guests",
    cap1000: "500+ guests",
    step1Title: "Contact Us",
    step1Desc: "Reach out via WhatsApp, phone or email.",
    step2Title: "Describe Your Issue",
    step2Desc: "Our specialist will listen and understand your needs.",
    step3Title: "Get a Solution",
    step3Desc: "A suitable solution will be offered as quickly as possible.",
    noServicesYet: "No services added yet",
    addFirstService: "Add Your First Service",
    newService: "New Service",
    logoSizeErr: "Logo cannot be larger than 5MB",
    logoUploadErr: "Logo could not be uploaded",
    slide1Title: "The Wedding of Your Dreams",
    slide1High: "Let's Build It Together",
    slide1Sub: "Azerbaijan's largest wedding services platform",
    slide2Title: "Perfect Venues",
    slide2High: "Premium Service",
    slide2Sub: "Baku's most prestigious wedding venues in one click",
    slide3Title: "Professional Photographers",
    slide3High: "Eternal Moments",
    slide3Sub: "Immortalize your special moments professionally",
    slide4Title: "Every Detail",
    slide4High: "For You",
    slide4Sub: "Cake, decor, music — everything on one platform",
    supportBlockTitle: "Professional Support Service",
    supportBlockDesc: "We are here for you 24/7. Get help with your wedding planning.",
    learnMore: "Learn more",
    testimonialsTitle: "Customer Reviews",
    testimonialsSub: "What our couples say about ToyQur.az",
    searchPlaceholder: "Search services... (e.g. photographer, venue)",
    searchBtn: "Search",
    profileManage: "Manage your personal details",
    blogBack: "Back to blog",
    articleNotFound: "Article not found",
    bp1p1: "2026 has brought new trends to the wedding world. Couples are choosing nature-inspired, simple yet elegant styles.",
    bp1p2: "White, cream, champagne and green tones dominate. Gold accessories add elegance.",
    bp1p3: "Technology continues to enter weddings: live streaming, drone footage.",
    bp1p4: "Locally sourced menus are trending. Geometric cake designs are popular.",
    bp1p5: "Live performers remain the top choice. Hybrid DJ formats are growing.",
    bp2p1: "Choosing a wedding photographer is one of the most important decisions. Photos last forever.",
    bp2p2: "First, research their style. Every photographer has a unique artistic approach.",
    bp2p3: "Second, check experience. At least 2-3 years of wedding photography is recommended.",
    bp2p4: "Third, review the contract and packages. Clarify delivery timelines upfront.",
    bp2p5: "Finally, meet in person. Chemistry matters a lot.",
    bp3p1: "Wedding decoration sets the atmosphere. The right choices can transform a simple venue.",
    bp3p2: "1. Color harmony: choose one main color and 2-3 complementary ones.",
    bp3p3: "2. Lighting: proper lighting creates 50% of the atmosphere. Warm LEDs and candles.",
    bp3p4: "3. Flowers: prefer seasonal flowers — fresh and budget-friendly.",
    bp3p5: "4. Table setting: choose a comfortable arrangement. Details matter.",
    bp3p6: "5. Entrance and photo zone: first impressions count. Photo zones for guests.",
    bp4p1: "Budget planning is the most important step to realizing your dream wedding.",
    bp4p2: "Step 1: Set your total budget. Keep 10-15% as a reserve.",
    bp4p3: "Step 2: Venue (40-50%), photo (10-12%), outfits (8-10%), decor (7-10%), music (5-8%).",
    bp4p4: "Step 3: Set your priorities. What matters most to you?",
    bp4p5: "Step 4: Compare prices. ToyQur.az brings all providers together.",
    bp4p6: "Step 5: Negotiate. Package discounts and off-peak pricing are available.",
    test1text: "Thanks to ToyQur.az we found all wedding services in one place. Everything was perfect!",
    test2text: "We found our photographer and decorator here. Results exceeded expectations. Thank you!",
    test3text: "Very convenient platform. Comparing prices and reading reviews helped a lot.",
    contactNow: "Contact Us Now",
    supportHelp: "We are happy to help you throughout the wedding planning process",
    googleLogin: "Sign in with Google",
    googleRegister: "Sign up with Google",
    orEmail: "or with email",
    authLoginSub: "Sign in to your account",
    authRegisterSub: "Create a new account",
    authForgotSub: "We will send a reset link to your email",
    editService: "Edit Service",
    addService: "Add New Service",
    saveService: "Save",
    addServiceBtn: "Add",
    submitting: "Please wait...",
    minSeatPrice: "Min seat price (₼)",
    maxSeatPrice: "Max seat price (₼)",
    minPrice: "Min price (₼)",
    maxPrice: "Max price (₼)",
    sortNewest: "Newest",
    sortRating: "Highest rated",
    sortPriceAsc: "Price: low to high",
    sortPriceDesc: "Price: high to low",
    sortOldest: "Oldest",
    allCities: "All cities",
    allDistricts: "All districts",
    select: "Select",
    noResults: "No results found",
    noServices: "No services",
    noResultsMsg: "No services found matching your filters. Try adjusting the filters.",
    noCatServices: "No services in this category yet.",
    resetFilters: "Reset filters",
    goHome: "Go to homepage",
    priceFilterLabel: "Price range (₼)",
    venuePriceLabel: "Per seat price (₼)",
    heroLine1: "The Wedding of Your Dreams",
    heroLine2: "Let's Build It Together",
    ctaTitle: "Are You a Service Provider?",
    ctaDesc: "Join our platform, reach thousands of couples and grow your business.",
    ctaBtn: "Register as a Service Provider",
    featuredOn: "On the Platform",
    featuredTitle: "All Services",
    seeAll: "See all",
    featuredSub: "Discover popular wedding services",
    sliderVenues: "Wedding Venues",
    sliderOutfits: "Bridal & Groom Outfits",
    sliderOther: "Other Services",
    contactTitle: "Contact",
    contactSub: "Get in touch — we're happy to help!",
    contactEmail: "Email",
    contactAddress: "Address",
    contactCity: "Baku, Azerbaijan",
    vendorCtaTitle: "Are you a service provider?",
    vendorCtaDesc: "Join the platform, reach thousands of couples and grow your business.",
    vendorCtaBtn: "Sign Up",
    sup1Title: "24/7 Support",
    sup1Desc: "We are here for you 7 days a week, 24 hours a day.",
    sup2Title: "Professional Team",
    sup2Desc: "Our experienced specialists help you find the best services.",
    sup3Title: "Reliable Service",
    sup3Desc: "All service providers are verified.",
    sup4Title: "Fast Response",
    sup4Desc: "Your requests are answered as quickly as possible.",
    supportTitle: "Professional Support Service",
    supportDesc: "ToyQur.az provides professional support at every stage of your wedding planning.",
    faqTitle: "More questions?",
    storeName: "Store Settings",
    storeDesc: "Customers will see all your products in one place",
    storeLogo: "Store Logo",
    storeLogoUpload: "Upload logo",
    storeBrandName: "Store / Brand name",
    storeAbout: "About the store",
    storeWA: "WhatsApp number",
    whatsappField: "WhatsApp number",
    whatsappRequired: "WhatsApp number is required",
    whatsappPlaceholder: "+994 XX XXX XX XX",
    editLimitReached: "You have already edited this service 2 times. No further edits are allowed.",
    editCountLeft: "Edits remaining",
    editCountOf: "of 2",
    svcUpdated: "Service updated. Awaiting re-approval.",
    svcAdded: "Service added. Awaiting approval.",
    fieldRequired: "Please enter title and category",
    priceRequired: "Please enter minimum price",
    phoneRequired2: "Phone number is required",
    logoRequired2: "Logo image is required",
    baRequired: "Full name and age are required for Bride Assistant",
    baSkillRequired: "At least one skill must be selected",
    storeAddress: "Address",
    completeProfile: "Complete your store",
    completeProfileMsg: "After filling in the logo, name and phone, you can add products.",
    completeProfileBtn: "Complete Profile",
    setupStore: "Create Your Store First",
    setupStoreMsg: "Set up your store before adding products.",
    setupStoreBtn: "Set Up Store",
    myStore: "My Store",
    manageServices: "Manage your services",
    svcCount: "My Services",
    deleteConfirm: "Are you sure you want to delete this service?",
    svcDeleted: "Service deleted",
    svcLoadErr: "Could not load services",
    profileFillRequired: "Please complete your profile first",
    profileWarningTitle: "Complete your profile",
    profileWarningMsg: "Name, surname and phone number must be filled in.",
    statusPending: "Pending",
    statusConfirmed: "Confirmed",
    statusRejected: "Rejected",
    statusCancelled: "Cancelled",
    confirmBooking: "Confirm",
    rejectBooking: "Reject",
    noBookings: "No bookings yet",
    bookingLoadErr: "Could not load bookings",
    addMedia: "Add",
    mapHint: "Find the location on Google Maps, tap Share → Copy link and paste here",
    formWarning: "After editing, the service will need to be re-approved.",
    formPhoneNote: "Phone numbers are only visible to the admin.",
    copyright: "© 2026 ToyQur.az — All rights reserved.",
    profileUpdated: "Profile updated!",
    passwordChanged: "Password changed successfully!",
    passwordChangeErr: "Could not change password",
    passwordMinErr: "Password must be at least 6 characters",
    defaultUser: "User",
    vendorStoreSuffix: "Store",
    defaultStoreName: "Vendor Store",
    productsCount: "products",
    catCount: "categories",
    aboutTitle: "About Us",
    aboutSub: "ToyQur.az is Azerbaijan's first and largest wedding services platform. Our goal is to help couples easily plan the wedding of their dreams.",
    missionTitle: "Our Mission",
    missionText: "To simplify the wedding planning process, connect service providers with clients, and help everyone realize their dream wedding.",
    feat1Title: "Passion",
    feat1Desc: "We believe every wedding is unique and special. We work with love.",
    feat2Title: "Wide Network",
    feat2Desc: "We collaborate with hundreds of professional service providers from every region of Azerbaijan.",
    feat3Title: "Reliability",
    feat3Desc: "All service providers are verified and client reviews are shared transparently.",
    feat4Title: "Quality",
    feat4Desc: "We only feature the best service providers on our platform.",
    blogSub: "Useful articles, professional tips and inspiring ideas about wedding planning",
    readMore: "Read more",
    myProfile: "My Profile",
    profileSub: "Manage your personal details",
    personalInfo: "Personal Information",
    fullNameLabel: "Full Name",
    phoneLabel: "Phone number",
    emailLabel: "Email",
    emailNote: "Email cannot be changed",
    emailVerified: "Email verified",
    saveChanges: "Save Changes",
    changePassTitle: "Change Password",
    newPassLabel: "New Password",
    confirmPassLabel: "Confirm new password",
    passNoMatch: "Passwords do not match",
    changing: "Changing...",
    favoritesTitle: "Favorites",
    favoritesLoginMsg: "Sign in to see your favorites",
    favoritesEmpty: "No favorites yet",
    favoritesEmptySub: "Browse services and save what you like",
    removeFromFav: "Remove from favorites",
    browseSvcs: "Browse Services",
    blog1Title: "Wedding Trends for 2026",
    blog1Excerpt: "Detailed information about the most popular colors, decoration styles and venue choices for weddings this year.",
    blog1Tag: "Trends",
    blog2Title: "How to Choose the Perfect Wedding Photographer",
    blog2Excerpt: "5 important things to pay attention to when choosing a wedding photographer.",
    blog2Tag: "Tips",
    blog3Title: "5 Essential Rules for Wedding Decoration",
    blog3Excerpt: "Key rules to consider when planning your wedding decoration.",
    blog3Tag: "Decor",
    blog4Title: "How to Plan Your Wedding Budget",
    blog4Excerpt: "Properly allocate your budget and make your dream wedding a reality.",
    blog4Tag: "Budget",
    sortNewest: "Newest first",
    sortRating: "Highest rated",
    sortPriceAsc: "Price: low to high",
    sortPriceDesc: "Price: high to low",
    sortOldest: "Oldest first",
    noResults: "No results found",
    noServices: "No services",
    noResultsDesc: "No services match your selected filters. Try changing the filters.",
    resetFilters: "Reset Filters",
    searchPlaceholder: "Search services...",
    filters: "Filters",
    priceVenue: "Per seat price (₼)",
    priceRange: "Price range (₼)",
    cityLabel: "City",
    allCities: "All cities",
    districtLabel: "District",
    allDistricts: "All districts",
    guestLabel: "Guest count",
    selectOption: "Select",
    searchHero: "Search services... (e.g. photographer, venue)",
    contactTitle: "Contact",
    contactSub: "Get in touch with us — we are happy to help!",
    contactPhone: "Phone",
    contactAddress: "Address",
    contactCity: "Baku, Azerbaijan",
    vendorCTA: "Are you a service provider?",
    vendorCTADesc: "Join our platform, reach thousands of couples and grow your business.",
    registerNow: "Register Now",
    sup1Title: "24/7 Support",
    sup1Desc: "We are here for you 7 days a week, 24 hours a day. Get help with wedding planning at any time.",
    sup2Title: "Professional Team",
    sup2Desc: "Our experienced wedding planning specialists will help you find the most suitable services.",
    sup3Title: "Reliable Service",
    sup3Desc: "All service providers are verified. We intervene as mediators if any problem arises.",
    sup4Title: "Fast Response",
    sup4Desc: "Your inquiries are answered as quickly as possible. Average response time is 15 minutes.",
    supStep1Title: "Contact Us",
    supStep1Desc: "Reach out via WhatsApp, phone or email.",
    supStep2Title: "Explain Your Issue",
    supStep2Desc: "Our specialist will listen and understand your needs.",
    supStep3Title: "Get a Solution",
    supStep3Desc: "A suitable solution will be offered to you in the shortest time.",
    vendorStoreFallback: "Vendor Store",
    heroSearchPlaceholder: "Search services... (e.g. photographer, venue)",
    "cat.wedding-hall": "Wedding Halls",
    "cat.banquet-hall": "Banquet Halls",
    "cat.photographer": "Photographer",
    "cat.videographer": "Videographer",
    "cat.cake": "Wedding Cake",
    "cat.xonca": "Xoncha",
    "cat.invitation": "Invitations",
    "cat.mc": "MC / Host",
    "cat.car": "Wedding Cars",
    "cat.decoration": "Decor & Design",
    "cat.music": "Live Music",
    "cat.dress": "Wedding Dress",
    "cat.groom-suit": "Groom Suit",
    "cat.dj": "DJ",
    "cat.singer": "Singer",
    "cat.dance-group": "Dance Group",
    "cat.beauty-salon": "Beauty Salon",
    
    "cat.bride-assistant": "Gəlin köməkçisi",
    "cat.mobilograf": "Mobiloqraf",
    "cat.buket": "Buket",
    "cat.gelinlik-buketi": "Gəlinlik buketi",
    "cat.group.venues": "Venues",
    "cat.group.other": "Other Services",
    favAdded: "Added to favorites",
    favRemoved: "Removed from favorites",
    favLogin: "Sign in to add to favorites",
    saveSuccess: "Saved!",
    brandSaved: "Store details saved!",
    logoRequired: "Store logo is required",
    phoneRequired: "Phone 1 is required",
    brandRequired: "Store name is required",
    saving: "Saving...",
    updating: "Updating...",
    loading: "Loading...",
    notFound: "Not found",
    error: "An error occurred",
  },
} as const;

export type TranslationKey = keyof typeof translations.az;

interface LanguageContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: TranslationKey) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  lang: "az",
  setLang: () => {},
  t: (key) => key,
});

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLangState] = useState<Lang>(() => {
    try { return (localStorage.getItem("lang") as Lang) || "az"; }
    catch { return "az"; }
  });

  const setLang = useCallback((l: Lang) => {
    localStorage.setItem("lang", l);
    setLangState(l);
  }, []);

  const t = useCallback((key: TranslationKey): string => {
    return translations[lang][key] ?? translations.az[key] ?? key;
  }, [lang]);

  useEffect(() => {
    document.documentElement.lang = lang;
  }, [lang]);

  const value = useMemo(() => ({ lang, setLang, t }), [lang, setLang, t]);

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);